Expense_Tracker/Expense_Tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls', namespace="users")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Expense_Tracker/core/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', startPage, name='home'),
    path('stocks/', StocksView.as_view(), name='stocks_graphs'),
    path('stocks_bag/', portfolio_view, name='stocks_bag'),
    path('transactions/', TransactionListView.as_view(), name='transaction_list'),
    path('transactions/upload/', TransactionUploadView.as_view(), name='upload_transactions'),
    path('transactions/delete-all/', TransactionDeleteAllView.as_view(), name='delete_all_transactions'),
    path('transactions/delete/<int:pk>/', TransactionDeleteView.as_view(), name='delete_transaction'),
]

Expense_Tracker/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path
from .views import *

app_name = "users"

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('password-change/', UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),

    path('register/', RegisterUser.as_view(), name='register'),
    path('profile/', ProfileUser.as_view(), name='profile'),
    path('add_account/', add_account, name='add_account'),
    path('delete_account/<int:pk>/', delete_account, name='delete_account'),
]

Expense_Tracker/core/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import ForeignKey


class StockInfo(models.Model):
    symbol = models.CharField(max_length=10, unique=True, verbose_name="Тикер")
    company_name = models.CharField(max_length=255, verbose_name="Название компании")
    sector = models.CharField(max_length=100, blank=True, null=True, verbose_name="Сектор")
    industry = models.CharField(max_length=100, blank=True, null=True, verbose_name="Отрасль")
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    country = models.CharField(max_length=100, blank=True, null=True, verbose_name="Страна")
    market_cap = models.FloatField(blank=True, null=True, verbose_name="Капитализация рынка")
    last_updated = models.DateTimeField(auto_now=True, verbose_name="Последнее обновление")

    def __str__(self):
        return f"{self.symbol} - {self.company_name}"

class Transaction(models.Model):
    operation_date = models.DateField(verbose_name="Дата операции")
    card_number = models.CharField(max_length=16, blank=True, verbose_name="Номер карты")
    currency = models.CharField(max_length=3, verbose_name="Валюта")
    category = models.CharField(max_length=50, blank=True, verbose_name="Категория")
    mcc = models.CharField(max_length=4, blank=True, verbose_name="MCC")
    description = models.TextField(verbose_name="Описание")
    bonuses = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Бонусы")
    amount = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Сумма")

    author = ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='posts', null=False, default=None)

    def __str__(self):
        return f"{self.operation_date} - {self.description}"


from django.db import models

class Stock(models.Model):
    figi = models.CharField(max_length=12, unique=True, verbose_name="FIGI")
    ticker = models.CharField(max_length=10, verbose_name="Тикер")
    name = models.CharField(max_length=255, verbose_name="Название компании")
    currency = models.CharField(max_length=3, verbose_name="Валюта")
    sector = models.CharField(max_length=100, blank=True, null=True, verbose_name="Сектор")
    country_of_risk = models.CharField(max_length=2, verbose_name="Код страны риска")
    country_of_risk_name = models.CharField(max_length=100, verbose_name="Страна риска")
    exchange = models.CharField(max_length=50, verbose_name="Торговая площадка")
    lot = models.IntegerField(verbose_name="Лотность")
    nominal = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, verbose_name="Номинал")
    trading_status = models.CharField(max_length=50, verbose_name="Режим торгов")
    ipo_date = models.DateField(blank=True, null=True, verbose_name="Дата IPO")

    def __str__(self):
        return f"{self.ticker} - {self.name}"

    class Meta:
        verbose_name = "Акция"
        verbose_name_plural = "Акции"


class Bond(models.Model):
    figi = models.CharField(max_length=12, unique=True, verbose_name="FIGI")
    ticker = models.CharField(max_length=10, verbose_name="Тикер")
    name = models.CharField(max_length=255, verbose_name="Название облигации")
    currency = models.CharField(max_length=3, verbose_name="Валюта")
    maturity_date = models.DateField(verbose_name="Дата погашения")
    nominal = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Номинал")
    coupon_quantity_per_year = models.IntegerField(verbose_name="Количество купонов в год")
    floating_coupon_flag = models.BooleanField(default=False, verbose_name="Плавающий купон")
    perpetual_flag = models.BooleanField(default=False, verbose_name="Бессрочная облигация")
    amortization_flag = models.BooleanField(default=False, verbose_name="Амортизация долга")
    exchange = models.CharField(max_length=50, verbose_name="Торговая площадка")
    trading_status = models.CharField(max_length=50, verbose_name="Режим торгов")

    def __str__(self):
        return f"{self.ticker} - {self.name}"

    class Meta:
        verbose_name = "Облигация"
        verbose_name_plural = "Облигации"


from django.db import models

Expense_Tracker/core/forms.py
from django import forms

from .functions import get_invest_info, get_token_accs_info, get_system_token

from users.models import *


class StockSelectionForm(forms.Form):
    def __init__(self, *args, **kwargs):
        # Извлекаем stock_options из kwargs
        stock_options = kwargs.pop('stock_options', [])

        # Вызываем родительский конструктор
        super().__init__(*args, **kwargs)

        # Сохраняем stock_options как атрибут формы
        self.stock_options = stock_options
        # Добавляем поле выбора с корректными choices
        self.fields['symbol'] = forms.ChoiceField(
            choices=self.stock_options,
            label="Select a stock"
        )

class TransactionUploadForm(forms.Form):
    file = forms.FileField(label="Выберите CSV файл")

class TransactionFilterForm(forms.Form):
    start_date = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={'type': 'date'}),
        label="Дата с"
    )
    end_date = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={'type': 'date'}),
        label="Дата по"
    )
    category = forms.ChoiceField(
        required=False,
        choices=[('', 'Все категории')] + [('Категория1', 'Категория1'), ('Категория2', 'Категория2')],  # Динамически заполняется
        label="Категория"
    )

from django import forms

class InstrumentSelectionForm(forms.Form):
    stock_figi = forms.ChoiceField(
        label="Select Stock",
        required=False,
        choices=[],
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    bond_figi = forms.ChoiceField(
        label="Select Bond",
        required=False,
        choices=[],
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    end_date = forms.DateField(
        label="End Date",
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'})
    )
    duration = forms.ChoiceField(
        label="Duration",
        choices=[
            ('1_hour', '1 Hour'),
            ('1_day', '1 Day'),
            ('1_week', '1 Week'),
            ('1_month', '1 Month'),
            ('1_year', '1 Year')
        ],
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    granularity = forms.ChoiceField(
        label="Data Granularity",
        choices=[
            ('1', '1 Minute'),
            ('5', '5 Minutes'),
            ('15', '15 Minutes'),
            ('60', '1 Hour'),
            ('1440', '1 Day')
        ],
        widget=forms.Select(attrs={'class': 'form-select'})
    )

    selected_asset = forms.CharField(
        label="Selected Asset",
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': True})
    )

    def __init__(self, *args, **kwargs):
        stocks = kwargs.pop('stocks', [])
        bonds = kwargs.pop('bonds', [])
        user = kwargs.pop('user', None)  # Получаем текущего пользователя

        super().__init__(*args, **kwargs)

        # Проверяем, что пользователь передан
        if not user:
            raise ValueError("Пользователь не передан в форму.")

        token = get_system_token(user=user)

        if get_token_accs_info(token) is None:
            portfolio_figi = []
        else:
            # Извлекаем FIGI активов из портфеля
            portfolio_figi = list(get_token_accs_info(token)['figi'])

        # Разделяем акции
        owned_stocks = []
        other_stocks = []
        for s in stocks:
            if s.figi in portfolio_figi:
                owned_stocks.append((s.figi, f"{s.name} ({s.figi})"))
                continue
            other_stocks.append((s.figi, f"{s.name} ({s.figi})"))

        # Разделяем облигации
        owned_bonds = []
        other_bonds = []
        for b in bonds:
            if b.figi in portfolio_figi:
                owned_bonds.append((b.figi, f"{b.name} ({b.figi})"))
                continue
            other_bonds.append((b.figi, f"{b.name} ({b.figi})"))

        # Формируем финальные списки выбора с разделителем
        if len(portfolio_figi) == 0:
            self.fields['stock_figi'].choices = other_stocks
        else:
            self.fields['stock_figi'].choices = (
                [('', '-- Мои акции --')] +
                owned_stocks +
                [('-', '--- Другие доступные активы ---')] +  # Разделитель
                other_stocks
            )

        if len(portfolio_figi) == 0:
            self.fields['bond_figi'].choices = other_bonds
        else:
            self.fields['bond_figi'].choices = (
                [('', '-- Мои облигации --')] +
                owned_bonds +
                [('-', '--- Другие доступные активы ---')] +  # Разделитель
                other_bonds
            )

    def clean(self):
        cleaned_data = super().clean()
        stock_figi = cleaned_data.get("stock_figi")
        bond_figi = cleaned_data.get("bond_figi")
        duration = cleaned_data.get("duration")
        granularity = int(cleaned_data.get("granularity"))

        # Проверяем, что выбран только один инструмент
        if stock_figi and bond_figi:
            raise forms.ValidationError("Выберите только одну ценную бумагу (акцию или облигацию).")

        if not stock_figi and not bond_figi:
            raise forms.ValidationError("Выберите акцию или облигацию.")

        # Проверяем соответствие интервала и продолжительности
        if granularity in [1, 5, 15] and duration not in ['1_hour', '1_day']:
            raise forms.ValidationError("Интервал 1, 5 или 15 минут доступен только для продолжительности 1 часа или 1 дня.")
        if granularity == 60 and duration not in ['1_hour', '1_day', '1_week']:
            raise forms.ValidationError("Интервал 1 час доступен только для продолжительности до 1 недели.")
        if granularity == 1440 and duration not in ['1_day', '1_week', '1_month', '1_year']:
            raise forms.ValidationError("Интервал 1 день доступен только для продолжительности до 1 года.")

        return cleaned_data


class AccountSelectionForm(forms.Form):
    account = forms.ModelChoiceField(
        queryset=Account.objects.none(),  # Пустой queryset (будет заполнен в представлении)
        label="Выберите счет",
        widget=forms.Select(attrs={'class': 'form-select'}),
        required=False
    )

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Фильтруем счета по текущему пользователю
        self.fields['account'].queryset = Account.objects.filter(author=user)

Expense_Tracker/core/templates/core/base.html
{% load static %}
<!doctype html>
<html lang="ru">
  <head>
    <!-- Обязательные метатеги -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- JS -->
    <script src="{% static 'core/fontawesomefree/js/all.min.js' %}"></script>
    <script src="{% static 'core/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'core/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'core/js/scripts.js' %}"></script>
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'core/fontawesomefree/css/all.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'core/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">


    <title>{{ title }}</title>
  </head>
  <body>

    <!-- Шапка сайта -->
    <nav class="navbar sticky-top navbar-expand-md navbar-light p-2">
        <div class="container-fluid">
            <!-- Логотип -->
            <a class="navbar-brand" href="{% url 'home' %}">bzbzApp</a>

            <!-- Кнопка для мобильной версии -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Основное меню -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <!-- Главная -->
                    <li class="nav-item mx-1">
                        <a class="nav-link" href="{% url 'home' %}">Главная</a>
                    </li>

                    <!-- Мой капитал (выпадающее меню) -->
                    <li class="nav-item mx-1">
                        <a class="nav-link" href="{% url 'transaction_list' %}">Мой капитал</a>
                    </li>
                    <!-- Рынок -->
                    <li class="nav-item dropdown mx-1">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Рынок
                        </a>
                        <ul class="dropdown-menu dropdown-menu-nav" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'stocks_graphs' %}">Котировки</a></li>
                            <li><a class="dropdown-item" href="{% url 'stocks_bag' %}">Мой Портфель</a></li>
                        </ul>
                    </li>

                </ul>

                <!-- Блок с профилем и выходом -->
                <ul class="navbar-nav ms-auto d-flex align-items-center">
                    {% if user.is_authenticated %}
                        <div class="nav-item btn-group dropstart mx-1">
                            <button type="button" class="btn btn-custom-2-nav dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                {{ user.username }}
                            </button>
                            <ul class="dropdown-menu dropdown-menu-nav" aria-labelledby="ProfileDropdown">
                                <li><a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a></li>
                                <li><a class="dropdown-item" href="{% url 'users:password_change' %}">Изменить пароль</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li>
                                    <div class="nav-item mt-1 text-center">
                                        <form method="post" action="{% url 'users:logout' %}" style="display: inline;">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-custom-1-nav">Выйти</button>
                                        </form>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    {% else %}
                        <!-- Вход и регистрация -->
                        <li class="nav-item">
                            <form method="post" action="{% url 'users:login' %}" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-custom-2-nav">Войти</button>
                            </form>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <!-- Футтер -->
    <footer class="container-fluid">
        <div class="container-fluid">
            <div class="row text-center">
                <div class="col-12">
                    <h2>Наши контакты</h2>
                </div>
                <div class="col-12 social padding">
                    <a href="#"><i class="fa-brands fa-youtube"></i></a>
                    <a href="#"><i class="fa-brands fa-instagram"></i></a>
                    <a href="#"><i class="fa-brands fa-github"></i></a>
                    <a href="#"><i class="fa-brands fa-google-drive"></i></a>
                </div>
            </div>
        </div>
    </footer>

  </body>
</html>

Expense_Tracker/core/templates/core/start.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}

<!-- Карусель -->
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>

  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'core/images/carousel_1.jpg' %}"}>
    </div>
    <div class="carousel-item">
      <img src="{% static 'core/images/carousel_2.jpg' %}"}>
    </div>
    <div class="carousel-item">
      <img src="{% static 'core/images/carousel_3.jpg' %}"}>
    </div>
    <div class="carousel-caption">
          <h1 class="display-2">Инвестирование</h1>
          <h3>Приумножьте свой капитал</h3>
          <a
                  class="btn btn-light btn-lg btn-custom-theory"
                  href="https://habr.com/ru/companies/dbtc/articles/527050/"
                  role="button"
                  target="_blank"
                  rel="noopener noreferrer"
          >
            Теория
          </a>
          <a
                  class="btn btn-light btn-lg btn-custom-doit"
                  href="https://www.tbank.ru/invest/stocks/"
                  role="button"
                  target="_blank"
                  rel="noopener noreferrer"
          >
            К делу!
          </a>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<!-- Вводная информация -->
<div class="container-fluid bg-secondary-subtle">
  <div class="row jumbotron align-items-center">
    <div class="col-md-9 col-lg-9 col-xl-10">
      <p class="lead">
        Для предоставления актуальной информации о котировках акций и облигаций мы
        используем Tinkoff Invest API — мощный и удобный инструмент, который
        обеспечивает доступ к данным с биржи в режиме реального времени.
        Это позволяет вам быть всегда в курсе изменений на рынке и оперативно
        реагировать на колебания цен.
      </p>
    </div>
    <div class="col-md-3 col-lg-3 col-xl-2">
      <a
              href="https://www.tbank.ru/finance/blog/invest-first-steps/"
              target="_blank"
              rel="noopener noreferrer"
      >
        <button class="btn btn btn-custom-3">Читать...</button>
      </a>
    </div>
  </div>
</div>
<!-- Что можно делать на сайте -->
<div class="container-fluid">
  <div class="row text-center alert">
    <div class="col-12">
      <h1 class="display-6">
        Аналитика
      </h1>
      <hr>
      <p class="lead">
        В современном мире управление личными финансами и инвестирование
        становятся неотъемлемой частью финансовой грамотности.
        Инвестирование позволяет не только сохранить свои сбережения,
        но и значительно увеличить их со временем.
        Однако успешное инвестирование требует не только знаний и стратегии,
        но и постоянного контроля над своими активами.
        Умение анализировать доходы, расходы и динамику котировок акций и
        облигаций помогает принимать взвешенные решения и минимизировать риски.
        Именно поэтому мы создали приложение, которое станет вашим надежным
        инструментом для управления финансами и отслеживания инвестиций.
      </p>
      <p class="lead">
        Наше приложение предлагает вам полный контроль над вашими финансами:
        вы можете легко следить за своими доходами и расходами,
        анализировать транзакции и планировать бюджет.
        Кроме того, вы получаете доступ к графикам цен на акции и облигации,
        что делает процесс инвестирования более прозрачным и понятным.
        Мы стремимся сделать управление финансами максимально удобным,
        наглядным и эффективным, чтобы вы могли сосредоточиться на
        достижении своих финансовых целей.
      </p>
      <p class="lead">
        Начните использовать наше приложение уже сегодня и сделайте шаг к стабильному
        финансовому будущему!
      </p>
    </div>
  </div>
</div>
<!-- Что можно делать на сайте (иконки)-->
<div class="container-fluid padding">
  <div class="row alert text-center padding">
    <div class="col-sm-12 col-md-6">
      <a href="{% url 'stocks_graphs'%}">
        <i class="fa-solid fa-money-bill-trend-up"></i>
      </a>
      <h3>Отслеживание цен</h3>
      <p>Треккинг котировок для своевременного принятия решений с использованием Tinkoff Invest API</p>
    </div>
    <div class="col-sm-12 col-md-6">
      <a href="{% url 'stocks_bag'%}">
        <i class="fa-solid fa-piggy-bank"></i>
      </a>
      <h3>Мой портфель</h3>
      <p>Мониторинг личного портфеля ценных бумаг в Тинькофф Инвестициях</p>
    </div>
    <hr class="my-4">
  </div>
</div>
<!-- Фиксированное изображение -->
<figure>
  <div class="fixed-wrap">
    <div id="fixed">

    </div>
  </div>
</figure>
<!-- Ссылка на статьи???-->
<div class="container-fluid padding">
  <br>
  <div class="row padding">
    <div class="offset-lg-2 col-lg-4">
      <h2>Что-то про инвестирование</h2>
      <p>
        Наше приложение создано для тех, кто хочет взять под контроль свои
        финансы и уверенно шагнуть в мир инвестирования.
        Мы сочетаем удобство, надежность и инновационные технологии,
        чтобы помочь вам достигать своих финансовых целей.
        Независимо от того, являетесь ли вы начинающим инвестором или
        опытным финансовым стратегом, наше приложение станет вашим верным
        помощником на пути к финансовому благополучию.
      </p>
      <br>
      <p>
        Начните использовать наше приложение уже сегодня и сделайте шаг
        к стабильному финансовому будущему!
      </p>
      <br>
    </div>
    <div class="col-lg-4">
      <br>
      <img src="{% static 'core/images/investment.jpg'%}" alt="" class="img-fluid">
    </div>
  <hr class="my-4">
  </div>
</div>
<!-- Гифки -->
<div class="text-center">
  <button type="button" id="gifs-button" class="btn btn-custom-3" data-bs-toggle="collapse" data-bs-target="#gifs">
    Открыть блок
  </button>
</div>
<div id="gifs" class="collapse">
  <div class="container-fluid padding">
    <div class="row text-center">
      <div class="col-sm-6 col-md-4">
        <img src="{% static 'core/images/gif-cafe.gif' %}" class="gif">
      </div>
      <div class="col-sm-6 col-md-4">
        <img src="{% static 'core/images/gif-cat.gif' %}" class="gif">
      </div>
      <div class="col-sm-6 col-md-4">
        <img src="{% static 'core/images/gif-witch.gif' %}" class="gif">
      </div>
    </div>
  </div>
</div>

{% endblock %}

Expense_Tracker/core/templates/core/stocks_bag.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid mt-5">

    <!-- Форма выбора аккаунта -->
    <div class="row justify-content-center">
        <div class="col-lg-10 p-4 bg-white shadow rounded">
            <form method="get" id="account-selection-form" class="row g-3">
                <h3 class="mb-4">Выбор аккаунта</h3>

                <!-- Выпадающий список аккаунтов -->
                <div class="col-md-6">
                    <label for="id_account" class="form-label">Аккаунт</label>
                    <select class="form-select" id="id_account" name="account">
                        <option value="">Выберите аккаунт</option>
                        {% for account in accounts %}
                            <option value="{{ account.id }}" {% if request.GET.account == account.id|stringformat:"s" %}selected{% endif %}>
                                {{ account.account_number }} ({{ account.token|truncatechars:16 }})
                            </option>
                        {% endfor %}
                    </select>
                </div>

                <!-- Кнопка "Применить" -->
                <div class="col-md-6 d-flex align-items-end justify-content-end">
                    <button type="submit" class="btn btn-lg btn-custom-2">Применить</button>
                </div>
            </form>
        </div>
    </div>

    <!-- Сообщение об ошибке -->
    {% if error %}
    <div class="alert alert-danger text-center" role="alert">
        {{ error }}
    </div>
    {% endif %}


    <!-- Диаграмма прибыли/убытков -->
    {% if chart_html %}
    <div class="row justify-content-center mx-4 my-4">
        <div class="col-12">
            {{ chart_html|safe }}
        </div>
    </div>
    {% endif %}

    <!-- Таблица доходов и расходов -->
    {% if table_data %}
    <div class="container-fluid offset-md-1 col-md-10 mt-2 mb-4 p-2">
        <h1>Детальная информация</h1>

        <table class="table table-striped table-hover">
            <thead class="table-dark">
                <tr>
                    <th scope="col">FIGI</th>
                    <th scope="col">Кол</th>
                    <th scope="col">Expected Yield</th>
                    <th scope="col">Type</th>
                    <th scope="col">Average Buy Price</th>
                    <th scope="col">Currency</th>
                    <th scope="col">Sell Sum</th>
                    <th scope="col">Commission</th>
                    <th scope="col">Tax</th>
                </tr>
            </thead>
            <tbody>
                {% for row in table_data %}
                <tr>
                    <td>{{ row.figi }}</td>
                    <td>{{ row.quantity }}</td>
                    <td>{{ row.expected_yield|floatformat:2 }}</td>
                    <td>{{ row.instrument_type }}</td>
                    <td>{{ row.average_buy_price|floatformat:2 }}</td>
                    <td>{{ row.currency }}</td>
                    <td>{{ row.sell_sum|floatformat:2 }}</td>
                    <td>{{ row.comission|floatformat:2 }}</td>
                    <td>{{ row.tax|floatformat:2 }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <!--Пагинация-->
        {% if page_obj.has_other_pages %}
        <nav aria-label="Page navigation" class="paginator">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?{{ query_params }}&page=1" aria-label="First">
                            <span aria-hidden="true">&laquo;&laquo;</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                <li class="page-item active">
                    <span class="page-link paginator-bar">
                        Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                    </span>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true" >&raquo;</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                            <span aria-hidden="true">&raquo;&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </div>
    {% else %}
    <div class="container-fluid padding mt-4">
        <div class="row text-center">
          <div class="col-sm-6 offset-md-3">
            <img src="{% static 'core/images/gif-cat.gif' %}" class="gif">
          </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}