Expense_Tracker/Expense_Tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls', namespace="users")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Expense_Tracker/core/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', startPage, name='home'),
    path('stocks/', StocksView.as_view(), name='stocks_graphs'),
    path('stocks_bag/', portfolio_view, name='stocks_bag'),
    path('transactions/', TransactionListView.as_view(), name='transaction_list'),
    path('transactions/upload/', TransactionUploadView.as_view(), name='upload_transactions'),
    path('transactions/delete-all/', TransactionDeleteAllView.as_view(), name='delete_all_transactions'),
    path('transactions/delete/<int:pk>/', TransactionDeleteView.as_view(), name='delete_transaction'),
]

Expense_Tracker/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path
from .views import *

app_name = "users"

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('password-change/', UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),

    path('register/', RegisterUser.as_view(), name='register'),
    path('profile/', ProfileUser.as_view(), name='profile'),
    path('add_account/', add_account, name='add_account'),
    path('delete_account/<int:pk>/', delete_account, name='delete_account'),
]

Expense_Tracker/users/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import ForeignKey

class Account(models.Model):
    account_number = models.CharField(max_length=20, unique=False, verbose_name="Номер счета")
    token = models.CharField(max_length=128, unique=False, verbose_name="Токен")

    author = ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='accounts', null=False, default=None)

    def __str__(self):
        return f"Счет {self.account_number} (Пользователь: {self.author.username})"

    class Meta:
        verbose_name = "Счет"
        verbose_name_plural = "Счета"


class SystemToken(models.Model):
    token = models.CharField(max_length=255, unique=False, verbose_name="Системный токен")
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='system_tokens',null=False, default=None)

    def __str__(self):
        return f"Токен {self.token} (Пользователь: {self.author.username})"

    class Meta:
        verbose_name = "Системный токен"
        verbose_name_plural = "Системные токены"

Expense_Tracker/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm

from .models import *

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(
        label='Логин или почта',
        widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Введите логин или email'})
    )
    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Введите пароль'})
    )

    error_messages = {
        "invalid_login": "Неверный логин или пароль.",
        "inactive": "Этот аккаунт неактивен.",
    }

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Подтвердите пароль', widget=forms.PasswordInput())
    email = forms.CharField(label='Email')

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']
        labels = {
            'email': 'Почта',
            'first_name': 'Имя',
            'last_name': 'Фамилия'
        }

        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name':forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой email уже существует")


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label='Почта',
                            widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'username', 'email']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия'
        }

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name':forms.TextInput(attrs={'class': 'form-input'}),
        }



class UserPasswordChange(PasswordChangeForm):
    old_password = forms.CharField(label='Старый пароль', widget=forms.PasswordInput())
    new_password1 = forms.CharField(label='Новый ароль', widget=forms.PasswordInput())
    new_password2 = forms.CharField(label='Подтвердите новый пароль', widget=forms.PasswordInput())


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['account_number', 'token']  # Поля для ввода
        widgets = {
            'account_number': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Номер счета'}),
            'token': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Токен'}),
        }
        labels = {
            'account_number': 'Номер счета',
            'token': 'Токен',
        }

class SystemTokenForm(forms.ModelForm):
    class Meta:
        model = SystemToken
        fields = ['token']
        widgets = {
            'token': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите системный токен'}),
        }
        labels = {
            'token': 'Системный токен',
        }

Expense_Tracker/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.http import HttpResponse, HttpResponseRedirect

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from .forms import *

class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': 'Профиль пользователя'}

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_initial(self):
        # Получаем начальные значения из текущего пользователя
        initial = super().get_initial()
        user = self.request.user
        initial['username'] = user.username
        initial['email'] = user.email
        initial['first_name'] = user.first_name
        initial['last_name'] = user.last_name
        return initial

    def get_context_data(self, **kwargs):
        # Добавляем форму для системного токена в контекст
        context = super().get_context_data(**kwargs)
        token_instance = SystemToken.objects.first()  # Получаем текущий токен
        context['token_form'] = SystemTokenForm(instance=token_instance)
        return context

    def post(self, request, *args, **kwargs):
        # Определяем, какая форма была отправлена
        if 'profile_form_submit' in request.POST:
            # Обработка формы профиля
            form = self.get_form()
            if form.is_valid():
                form.save()
                messages.success(request, 'Профиль успешно обновлен.')
                return self.form_valid(form)
            else:
                return self.form_invalid(form)

        elif 'token_form_submit' in request.POST:
            # Обработка формы системного токена
            token_instance = SystemToken.objects.first()
            token_form = SystemTokenForm(request.POST, instance=token_instance)
            if token_form.is_valid():
                token_form.save()
                messages.success(request, 'Системный токен успешно обновлен.')
                return redirect('users:profile')
            else:
                # Если форма токена невалидна, передаем её в контекст
                context = self.get_context_data()
                context['token_form'] = token_form
                return self.render_to_response(context)

class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}

class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('users:login')

class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': 'Профиль пользователя'}

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_initial(self):
        # Получаем начальные значения из текущего пользователя
        initial = super().get_initial()
        user = self.request.user
        initial['username'] = user.username
        initial['email'] = user.email
        initial['first_name'] = user.first_name
        initial['last_name'] = user.last_name
        return initial

    def get_context_data(self, **kwargs):
        # Добавляем форму для системного токена в контекст
        context = super().get_context_data(**kwargs)
        token_instance = SystemToken.objects.filter(author=self.request.user).first()  # Получаем текущий токен
        context['token_form'] = SystemTokenForm(instance=token_instance)
        return context

    def post(self, request, *args, **kwargs):
        # Инициализируем self.object
        self.object = self.get_object()

        # Определяем, какая форма была отправлена
        if 'profile_form_submit' in request.POST:
            # Обработка формы профиля
            form = self.get_form()
            if form.is_valid():
                form.save()
                messages.success(request, 'Профиль успешно обновлен.')
                return self.form_valid(form)
            else:
                return self.form_invalid(form)

        elif 'token_form_submit' in request.POST:
            # Обработка формы системного токена
            token_instance = SystemToken.objects.filter(author=request.user).first()
            token_form = SystemTokenForm(request.POST, instance=token_instance)
            if token_form.is_valid():
                # Удаляем старые токены перед сохранением нового
                SystemToken.objects.filter(author=request.user).delete()
                new_token = token_form.save(commit=False)
                new_token.author = request.user
                new_token.save()
                messages.success(request, 'Системный токен успешно обновлен.')
                return redirect('users:profile')
            else:
                # Если форма токена невалидна, передаем её в контекст
                context = self.get_context_data()
                context['token_form'] = token_form
                return self.render_to_response(context)

@login_required
def add_account(request):
    if request.method == 'POST':
        form = AccountForm(request.POST)
        if form.is_valid():
            account = form.save(commit=False)
            account.author = request.user  # Привязываем аккаунт к текущему пользователю
            account.save()
            messages.success(request, 'Счет успешно добавлен.')
            return redirect('users:profile')
    else:
        form = AccountForm()

    return render(request, 'users/add_account.html', {'form': form,
                                                                           'title': 'Добавить аккаунт',})

@login_required
def delete_account(request, pk):
    account = get_object_or_404(Account, pk=pk, author=request.user)
    if request.method == 'POST':
        account.delete()
        messages.success(request, 'Счет успешно удален.')
    return redirect('users:profile')

class UserPasswordChange(PasswordChangeView):
    form_class = PasswordChangeForm
    template_name = 'users/password_change.html'
    extra_context = {'title': 'Смена пароля'}

    def get_success_url(self):
        return  reverse_lazy('users:password_change_done')

Expense_Tracker/users/templates/users/add_account.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}
<div class="card shadow-lg p-3 bg-light col-xs-10 col-md-6 offset-xs-1 offset-md-3">
    <div class="card-body">
        <h1 class="fw-normal text-center h2 mb-4">Добавить счет</h1>

        <form method="post">
            {% csrf_token %}

            <!-- Отображение глобальных ошибок -->
            {% if form.non_field_errors %}
            <div class="alert alert-danger my-3" role="alert">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
            {% endif %}

            <!-- Поля формы -->
            {% for f in form %}
            <div class="form-floating mb-3">
                <input
                    type="{{ f.field.widget.input_type }}"
                    class="form-control"
                    id="{{ f.id_for_label }}"
                    name="{{ f.html_name }}"
                    placeholder="{{ f.label }}"
                    value="{{ f.value|default_if_none:'' }}"
                >
                <label for="{{ f.id_for_label }}">{{ f.label }}</label>
            </div>
            <div class="form-error text-danger mb-3">{{ f.errors }}</div>
            {% endfor %}

            <!-- Кнопка сохранения -->
            <div class="text-center col-md-6 offset-md-3">
                <button class="w-100 btn btn-lg btn-custom-2" type="submit">Добавить</button>
            </div>
        </form>

        <!-- Ссылка на профиль -->
        <div class="my-3 text-center">
            <a href="{% url 'users:profile' %}" class="text-decoration-none">Вернуться в профиль</a>
        </div>
    </div>
</div>
{% endblock %}

Expense_Tracker/users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- JS -->
    <script src="{% static 'users/fontawesomefree/js/all.min.js' %}"></script>
    <script src="{% static 'users/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'users/fontawesomefree/css/all.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'users/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">

    <title>{{ title }}</title>
</head>
<body class="d-flex align-items-center justify-content-center min-vh-100 bg-dark">
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

Expense_Tracker/users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
<div class="card shadow-lg px-3 pt-3 bg-light col-xs-10 col-md-6 offset-xs-1 offset-md-3">
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}" />

            <h1 class="fw-normal text-center h2 mb-4">Добро пожаловать!</h1>

            <div class="form-floating">
              <input
                type="text"
                class="form-control"
                id="{{ form.username.id_for_label }}"
                name="{{ form.username.html_name }}"
                placeholder="Логин или email">
              <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
            </div>
            <div class="form-floating">
              <input
                type="password"
                class="form-control"
                id="{{ form.password.id_for_label }}"
                name="{{ form.password.html_name }}"
                placeholder="Password">
              <label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
            </div>

            <!-- Отображение глобальных ошибок -->
            {% if form.non_field_errors %}
            <div class="container-fluid col-md-12 d-flex justify-content-start">
                <div class="row alert alert-danger mt-3 mx-0 px-3 w-100">
                    {% for error in form.non_field_errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            </div>
            {% endif %}

            <div class="checkbox my-3">
              <label>
                <input type="checkbox" value="remember-me"> Запомнить
              </label>
            </div>
            <div class="text-center col-md-4 offset-md-4">
                <!-- Кастомная кнопка -->
                <button class="w-100 btn btn-lg btn-custom-2" type="submit">Войти</button>
            </div>

            <!-- Ссылка на регистрацию -->
            <div class="text-center my-3">
                <a href="{% url 'users:register' %}" class="text-decoration-none">Еще нет аккаунта? Зарегистрируйтесь!</a>
            </div>

        </form>
    </div>
</div>
{% endblock %}

Expense_Tracker/users/templates/users/password_change.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}
<div class="card shadow-lg px-3 pt-3 bg-light col-xs-10 col-md-6 offset-xs-1 offset-md-3">
    <div class="card-body">
        <form method="post">
            {% csrf_token %}

            <h1 class="fw-normal text-center h2 mb-4">Смена пароля</h1>

            <!-- Отображение глобальных ошибок -->
            {% if form.non_field_errors %}
            <div class="alert alert-danger my-3" role="alert">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
            {% endif %}

            <!-- Поля формы -->
            {% for f in form %}
            <div class="form-floating mb-3">
                <input
                    type="{{ f.field.widget.input_type }}"
                    class="form-control"
                    id="{{ f.id_for_label }}"
                    name="{{ f.html_name }}"
                    placeholder="{{ f.label }}"
                    value="{{ f.value|default_if_none:'' }}"
                >
                <label for="{{ f.id_for_label }}">{{ f.label }}</label>
            </div>
            <div class="form-error text-danger mb-3">{{ f.errors }}</div>
            {% endfor %}

            <!-- Кнопка отправки -->
            <div class="text-center col-md-6 offset-md-3">
                <button class="w-100 btn btn-lg btn-custom-2" type="submit">Изменить пароль</button>
            </div>

            <!-- Ссылка на профиль -->
            <div class="my-3">
                <a href="{% url 'users:profile' %}" class="text-decoration-none">Вернуться в профиль</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

Expense_Tracker/users/templates/users/password_change_done.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}
<div class="card shadow-lg px-3 pt-3 bg-light col-xs-10 col-md-6 offset-xs-1 offset-md-3">
    <div class="card-body text-center">
        <!-- Заголовок -->
        <h1 class="fw-normal text-center h2 mb-4">Пароль успешно изменен!</h1>

        <!-- Сообщение -->
        <p class="lead">Вы успешно изменили пароль.</p>

        <!-- Ссылка на профиль -->
        <div class="text-center my-3">
            <a href="{% url 'users:profile' %}" class="btn btn-custom-2">Вернуться в профиль</a>
        </div>
    </div>
</div>
{% endblock %}

Expense_Tracker/users/templates/users/profile.html
{% extends 'users/base.html' %}
{% load static %}
{% load custom_filters %}

{% block content %}
<div class="card shadow-lg px-3 pt-3 bg-light col-xs-10">
    <div class="card-body row">
        <div class="col-md-4">
            <h1 class="fw-normal h2 mb-4">Профиль</h1>

            <!-- Форма редактирования профиля -->
            <form method="post">
                {% csrf_token %}

                <!-- Отображение глобальных ошибок -->
                {% if form.non_field_errors %}
                <div class="alert alert-danger my-3" role="alert">
                    {% for error in form.non_field_errors %}
                        {{ error }}
                    {% endfor %}
                </div>
                {% endif %}

                <!-- Поля формы -->
                {% for f in form %}
                <div class="form-floating mb-3">
                    <input
                        type="{{ f.field.widget.input_type }}"
                        class="form-control"
                        id="{{ f.id_for_label }}_1"
                        name="{{ f.html_name }}"
                        placeholder="{{ f.label }}"
                        value="{{ f.value|default_if_none:'' }}"
                    >
                    <label for="{{ f.id_for_label }}_1">{{ f.label }}</label>
                </div>
                <div class="form-error text-danger mb-3">{{ f.errors }}</div>
                {% endfor %}

                <!-- Кнопка сохранения -->
                <div class="text-center col-md-6 offset-md-3">
                    <button class="w-100 btn btn-lg btn-custom-2" type="submit">Сохранить</button>
                </div>
            </form>

            <!-- Ссылки -->
            <div class="my-3">
                <a href="{% url 'users:password_change' %}" class="text-decoration-none">Сменить пароль</a>
            </div>
            <div class="my-3">
                <a href="{% url 'home' %}" class="text-decoration-none">Вернуться на главную страницу</a>
            </div>
        </div>

        <!-- Таблица аккаунтов -->
        <div class="offset-md-1 col-md-6">
            <h3 class="fw-normal h3 mt-5">Мои счета</h3>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Номер счета</th>
                        <th>Токен</th>
                        <th class="">Действия</th>
                    </tr>
                </thead>
                <tbody>
                    {% for account in user.accounts.all %}
                    <tr>
                        <td>{{ account.account_number }}</td>
                        <td>{{ account.token|truncate_token:16}}</td>
                        <td>
                            <form method="post" action="{% url 'users:delete_account' account.id %}" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-sm btn-custom-1" onclick="return confirm('Вы уверены, что хотите удалить этот счет?');">
                                    Удалить
                                </button>
                            </form>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="3" class="text-center">Нет счетов.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <!--Пагинация-->
            {% if page_obj.has_other_pages %}
            <nav aria-label="Page navigation" class="paginator">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?{{ query_params }}&page=1" aria-label="First">
                                <span aria-hidden="true">&laquo;&laquo;</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}

                    <li class="page-item active">
                        <span class="page-link paginator-bar">
                            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                        </span>
                    </li>

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true" >&raquo;</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                                <span aria-hidden="true">&raquo;&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}

            <!-- Ссылка на добавление нового счета -->
            <div class="my-3 text-center">
                <a href="{% url 'users:add_account' %}" class="btn btn-sm btn-primary btn-custom-2">Добавить счет</a>
            </div>

            <!-- Форма редактирования системного токена -->
            <div class="col-md-12 mt-5">
            <h3 class="fw-normal h3">Системный токен</h3>
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="token_form_submit" value="1">

                <!-- Поля формы -->
                {% for f in token_form %}
                <div class="form-floating mb-3">
                    <input
                        type="{{ f.field.widget.input_type }}"
                        class="form-control"
                        id="{{ f.id_for_label }}"
                        name="{{ f.html_name }}"
                        placeholder="{{ f.label }}"
                        value="{{ f.value|default_if_none:'' }}"
                    >
                    <label for="{{ f.id_for_label }}">{{ f.label }}</label>
                </div>
                <div class="form-error text-danger mb-3">{{ f.errors }}</div>
                {% endfor %}

                <!-- Кнопка сохранения -->
                <div class="text-center col-md-6 offset-md-3">
                    <button class="btn btn-sm btn-custom-2" type="submit">Сохранить токен</button>
                </div>
            </form>
        </div>

        </div>
    </div>
</div>
{% endblock %}